spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ShareMind?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://sharemind-db:3306/ShareMind?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234

  redis:
#    host: localhost
    host: redis
    port: 6379
    password: c204


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9a207ca169983309ce2fe15d2c1831da
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: http://i7c204.p.ssafy.io:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id



jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-in-seconds: 1800
  refresh-token-validity-in-seconds: 86400

front:
#  url: http://localhost:8080/test
  url: http://localhost:3000/oauth/callback


logging:
  level:
    org:
      hibernate:
        SQL: debug
#        type:
#          descriptor:
#            sql: trace
